app = "calendar-assistant"
primary_region = "arn" # Change this to your preferred region
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  # Environment variables will be set through the Fly.io secrets

[mounts]
  source = "calendar_assistant_tmp_data"
  destination = "/app/tmp"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 